config/routes.rb
Chw::Application.routes.draw do
  resources :tblocationreports

  resources :tbdotreports

  resources :dotsmembers

  resources :tbcases

  resources :hivdrugreports

  resources :hivcontraceptionreports

  resources :hivlocationreports

  resources :hivgenderreports

  resources :hivcases

  resources :malariapreventationreports

  resources :malariagenderreports

  resources :malarialocationreports

  resources :patients

  resources :malariacases

  resources :smsmessages

resources :locations
resources :settings
resources :villageworkers
resources :malaria
resources :tb
resources :hivaid
resources :childhealth
resources :immunization
resources :test_it

resources :communityhealthworker
get "textmessage/new"
resources :communityworkers

resources :sms

get 'admin' => 'admin#index'
get 'lol' => 'session#create'

resources :messages

controller :textmessage do 
get 'textmessage' => :show
end 

controller :sessions do    	
  	get 'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
	end 
resources :users

 

   root :to => 'admin#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/dotsmember.rb
require 'tb/dotsprocessor'
class Dotsmember < ActiveRecord::Base

def executeSmsCommand(smsCommand)
	@new_dots_member = Dotsprocessor.new(smsCommand)
	return @new_dots_member.executeCommand(self)
end 

end

app/models/hivcase.rb
require 'hiv/hivprocessor'
class Hivcase < ActiveRecord::Base

def executeSmsCommand(smsCommand)
	@newHivCase = Hivprocessor.new(smsCommand)
	return @newHivCase.executeCommand(self)
end 

end

app/models/hivdrugreport.rb
require 'hiv/drugsrpt'

class Hivdrugreport < ActiveRecord::Base


def drawDrugGraph(locationName,locationId,year)
@hiv_drug_rpt = Hivdrugrpt.new
@hiv_drug_rpt.executeCommand(locationName,locationId,year) #draw a graph with the title command 
end



end

app/models/location.rb
class Location < ActiveRecord::Base
has_many :villageworkers
end

app/models/malariacase.rb
require 'malaria/malariaprocessor'

class Malariacase < ActiveRecord::Base
belongs_to :patients, :foreign_key => :patient_id, :class_name => "Patient"

def executeSmsCommand(command)
@newmalariaCase = Malariaprocessor.new(command)
@newmalariaCase.executeCommand(self)
end 

end 

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/messageparser.rb
class Messageparser < ActiveRecord::Base

def render
end 

end

app/models/patient.rb
require 'patients/patientprocessor'

class Patient < ActiveRecord::Base

has_many :malariacases
belongs_to :villageworker,:foreign_key => "communityworker_id"
belongs_to :location

def executeSmsCommand(phone,smscommand)
@patientProcessor = Patientprocessor.new(phone,smscommand)
@patientProcessor.executeCommand(self)
end

end

app/models/sm.rb
class Sm < ActiveRecord::Base
def render
"Thank you , a new patient has been registered"
end 
end

app/models/smsmessage.rb
require 'textmessageparser/smsparser.rb'

class Smsmessage < ActiveRecord::Base


def render(phone_number,message)
@smsparser = Textmessageparser.new(phone_number,message)
@smsparser.render
end 


end

app/models/tbcase.rb
require 'tb/tbprocessor'
class Tbcase < ActiveRecord::Base

def executeSmsCommand(command)
@newtbCase = Tbprocessor.new(command)
@newtbCase.executeCommand(self)
end 
end

app/models/tbdotreport.rb
require 'tb/dotrpt'
class Tbdotreport < ActiveRecord::Base

def drawDotsGraph(title)
@tb_dots_rpt = Dotrpt.new
@tb_dots_rpt.executeCommand(title) #draw a graph with the title command 
end


end

app/models/text_message.rb
class TextMessage < ActiveRecord::Base
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
validates :name, :presence => true, :uniqueness => true 

validates :password, :confirmation => true 

attr_accessor :password_confirmation 
attr_reader :password 

validate :password_must_be_present

class << self 
def authenticate(name,password)
if user = find_by_name(name)
if user.hashed_password == encrypt_password(password,user.salt)
user
end 
end 
end 


def encrypt_password(password,salt)
Digest::SHA2.hexdigest(password + "village" +salt)
end
end  

def password=(password)
@password = password 

if password.present?
generate_salt
self.hashed_password = self.class.encrypt_password(password,salt)
end
end 


private 

def password_must_be_present
errors.add(:password, "Missing passwords") unless hashed_password.present?
end 

def generate_salt
self.salt = self.object_id.to_s + rand.to_s 
end
end

app/models/village.rb
class Village < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/helpers/tb_helper.rb
module TbHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_admin_menu.html.erb
<div id="menu8">
  <ul>
    <li><%= link_to "Dashboard", sms_path%> </li>
   <li><%= link_to "New Worker", new_villageworker_path%> </li>
    <li><%= link_to "All Workers", villageworkers_path%> </li>
  	<li><%= link_to "New Patient", new_patient_path %></li>
    <li><%= link_to "All Patients", patients_path %></li>

  </ul>
</div>

app/views/admin/_footer.html.erb
<div class="footer">
Produced by Eric Kiilu As a 2nd Year Project, University of Nairobi
</div>
</body>
</html>

app/views/admin/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chw</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "style", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
<div class="logo">
<%= image_tag("CHW-Good.jpg") %>
</div>
<div class="user_login">
Welcome 
<%= session[:user_name] %>
<%= link_to "Logout","logout"%>
</div>
</div>



<div class="top_menu">
<%= render "admin/menu" %>
</div>

app/views/admin/_menu.html.erb
<ul>
<li><%= link_to 'Home', admin_path %> <li>
<li><%= link_to 'Locations', locations_path %> <li>
<li><%= link_to 'Malaria', malaria_path %></li>
<li><%= link_to 'HIV and AIDS', "/hivaid" %>  </li>
<li><%= link_to 'TB', '/tb' %>  </li>
<li><%= link_to 'Settings', settings_path %></li>
</ul>

app/views/admin/index.html.erb
<h1>Community Health Worker </h1>

app/views/communityworker/new.html.erb
<%= form_for @communityworker do |f| %>
<%= f.text_field :firstname %>
<% f.submit "Save" %>
<% end %>