config/routes.rb
Chw::Application.routes.draw do
  resources :tblocationreports

  resources :tbdotreports

  resources :dotsmembers

  resources :tbcases

  resources :hivdrugreports

  resources :hivcontraceptionreports

  resources :hivlocationreports

  resources :hivgenderreports

  resources :hivcases

  resources :malariapreventationreports

  resources :malariagenderreports

  resources :malarialocationreports

  resources :patients

  resources :malariacases

  resources :smsmessages

resources :locations
resources :settings
resources :villageworkers
resources :malaria
resources :tb
resources :hivaid
resources :childhealth
resources :immunization
resources :test_it

resources :communityhealthworker
get "textmessage/new"
resources :communityworkers

resources :sms

get 'admin' => 'admin#index'
get 'lol' => 'session#create'

resources :messages

controller :textmessage do 
get 'textmessage' => :show
end 

controller :sessions do    	
  	get 'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
	end 
resources :users

 

   root :to => 'admin#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/dotsmember.rb
require 'tb/dotsprocessor'
class Dotsmember < ActiveRecord::Base

def executeSmsCommand(smsCommand)
	@new_dots_member = Dotsprocessor.new(smsCommand)
	return @new_dots_member.executeCommand(self)
end 

end

app/models/hivcase.rb
require 'hiv/hivprocessor'
class Hivcase < ActiveRecord::Base

def executeSmsCommand(smsCommand)
	@newHivCase = Hivprocessor.new(smsCommand)
	return @newHivCase.executeCommand(self)
end 

end

app/models/hivdrugreport.rb
require 'hiv/drugsrpt'

class Hivdrugreport < ActiveRecord::Base


def drawDrugGraph(locationName,locationId,year)
@hiv_drug_rpt = Hivdrugrpt.new
@hiv_drug_rpt.executeCommand(locationName,locationId,year) #draw a graph with the title command 
end



end

app/models/location.rb
class Location < ActiveRecord::Base
has_many :villageworkers
end

app/models/malariacase.rb
require 'malaria/malariaprocessor'

class Malariacase < ActiveRecord::Base
belongs_to :patients, :foreign_key => :patient_id, :class_name => "Patient"

def executeSmsCommand(command)
@newmalariaCase = Malariaprocessor.new(command)
@newmalariaCase.executeCommand(self)
end 

end 

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/messageparser.rb
class Messageparser < ActiveRecord::Base

def render
end 

end

app/models/patient.rb
require 'patients/patientprocessor'

class Patient < ActiveRecord::Base

has_many :malariacases
belongs_to :villageworker,:foreign_key => "communityworker_id"
belongs_to :location

def executeSmsCommand(phone,smscommand)
@patientProcessor = Patientprocessor.new(phone,smscommand)
@patientProcessor.executeCommand(self)
end

end

app/models/sm.rb
class Sm < ActiveRecord::Base
def render
"Thank you , a new patient has been registered"
end 
end

app/models/smsmessage.rb
require 'textmessageparser/smsparser.rb'

class Smsmessage < ActiveRecord::Base


def render(phone_number,message)
@smsparser = Textmessageparser.new(phone_number,message)
@smsparser.render
end 


end

app/models/tbcase.rb
require 'tb/tbprocessor'
class Tbcase < ActiveRecord::Base

def executeSmsCommand(command)
@newtbCase = Tbprocessor.new(command)
@newtbCase.executeCommand(self)
end 
end

app/models/tbdotreport.rb
require 'tb/dotrpt'
class Tbdotreport < ActiveRecord::Base

def drawDotsGraph(title)
@tb_dots_rpt = Dotrpt.new
@tb_dots_rpt.executeCommand(title) #draw a graph with the title command 
end


end

app/models/text_message.rb
class TextMessage < ActiveRecord::Base
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
validates :name, :presence => true, :uniqueness => true 

validates :password, :confirmation => true 

attr_accessor :password_confirmation 
attr_reader :password 

validate :password_must_be_present

class << self 
def authenticate(name,password)
if user = find_by_name(name)
if user.hashed_password == encrypt_password(password,user.salt)
user
end 
end 
end 


def encrypt_password(password,salt)
Digest::SHA2.hexdigest(password + "village" +salt)
end
end  

def password=(password)
@password = password 

if password.present?
generate_salt
self.hashed_password = self.class.encrypt_password(password,salt)
end
end 


private 

def password_must_be_present
errors.add(:password, "Missing passwords") unless hashed_password.present?
end 

def generate_salt
self.salt = self.object_id.to_s + rand.to_s 
end
end

app/models/village.rb
class Village < ActiveRecord::Base
end

app/controllers/tbcases_controller.rb
class TbcasesController < ApplicationController
  # GET /tbcases
  # GET /tbcases.json

layout "tb"

  def index
    @tbcases = Tbcase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tbcases }
    end
  end

  # GET /tbcases/1
  # GET /tbcases/1.json
  def show
    @tbcase = Tbcase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tbcase }
    end
  end

  # GET /tbcases/new
  # GET /tbcases/new.json
  def new
    @tbcase = Tbcase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tbcase }
    end
  end

  # GET /tbcases/1/edit
  def edit
    @tbcase = Tbcase.find(params[:id])
  end

  # POST /tbcases
  # POST /tbcases.json
  def create
    @tbcase = Tbcase.new(params[:tbcase])

    respond_to do |format|
      if @tbcase.save
        format.html { redirect_to @tbcase, notice: 'Tbcase was successfully created.' }
        format.json { render json: @tbcase, status: :created, location: @tbcase }
      else
        format.html { render action: "new" }
        format.json { render json: @tbcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tbcases/1
  # PUT /tbcases/1.json
  def update
    @tbcase = Tbcase.find(params[:id])

    respond_to do |format|
      if @tbcase.update_attributes(params[:tbcase])
        format.html { redirect_to @tbcase, notice: 'Tbcase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tbcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tbcases/1
  # DELETE /tbcases/1.json
  def destroy
    @tbcase = Tbcase.find(params[:id])
    @tbcase.destroy

    respond_to do |format|
      format.html { redirect_to tbcases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/helpers/tb_helper.rb
module TbHelper
end

app/helpers/tbcases_helper.rb
module TbcasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tbcases/_form.html.erb
<%= form_for(@tbcase) do |f| %>
  <% if @tbcase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tbcase.errors.count, "error") %> prohibited this tbcase from being saved:</h2>

      <ul>
      <% @tbcase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_reported %><br />
    <%= f.date_select :date_reported %>
  </div>
  <div class="field">
    <%= f.label :patient_number %><br />
    <%= f.text_field :patient_number %>
  </div>
  <div class="field">
    <%= f.label :availability_of_drugs %><br />
    <%= f.text_field :availability_of_drugs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tbcases/edit.html.erb
<h1>Editing tbcase</h1>

<%= render 'form' %>

<%= link_to 'Show', @tbcase %> |
<%= link_to 'Back', tbcases_path %>

app/views/tbcases/index.html.erb
<h1>Listing  All Tb Cases</h1>

<table class="table_list">
  <tr>
    <th>Date reported</th>
    <th>Patient number</th>
    <th>Availability of drugs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tbcases.each do |tbcase| %>
  <tr>
    <td><%= tbcase.date_reported %></td>
    <td><%= tbcase.patient_number %></td>
    <td><%= tbcase.availability_of_drugs %></td>
    <td><%= link_to 'Show', tbcase %></td>
    <td><%= link_to 'Edit', edit_tbcase_path(tbcase) %></td>
    <td><%= link_to 'Destroy', tbcase, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tbcases/new.html.erb
<h1>Manually Add a New Tb Case</h1>

<%= render 'form' %>

app/views/tbcases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date reported:</b>
  <%= @tbcase.date_reported %>
</p>

<p>
  <b>Patient number:</b>
  <%= @tbcase.patient_number %>
</p>

<p>
  <b>Availability of drugs:</b>
  <%= @tbcase.availability_of_drugs %>
</p>


<%= link_to 'Edit', edit_tbcase_path(@tbcase) %> |
<%= link_to 'Back', tbcases_path %>